version: "3"
volumes:
  database:
    driver: local

networks:
  apple-si-gaming-db-network:
services:
  postgres:
    platform: linux/amd64
    image: postgres:latest
    restart: always
    container_name: postgres
    networks:
      - apple-si-gaming-db-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      # - ./dump.sql:/docker-entrypoint-initdb.d/create_tables.sql

  remix-app:
    image: apple-si-gaming-db/remix-app:0.0.2
    container_name: remix-app
    # entrypoint: yarn --cwd apps/remix-app start
    networks:
      - apple-si-gaming-db-network
    depends_on:
      - postgres
    env_file:
      - .env.stage.env
    ports:
      - 8080:8080
    links:
      - "postgres:db"

  backend-ops:
    image: apple-si-gaming-db/backend-ops:0.0.1
    networks:
      - apple-si-gaming-db-network
    depends_on:
      - postgres
    env_file:
      - .env.stage.env
    links:
      - "postgres:db"
    
  # mysql:
  #   platform: linux/amd64
  #   image: mysql:8.0.28
  #   container_name: turborepo_mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: turborepo
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #     - database:/var/lib/mysql
