version: "3"
volumes:
  database:
    driver: local

services:
  postgres:
    platform: linux/amd64
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      # - ./dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
    
  # mysql:
  #   platform: linux/amd64
  #   image: mysql:8.0.28
  #   container_name: turborepo_mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: turborepo
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #     - database:/var/lib/mysql
