version: "3"
volumes:
  database:
    driver: local

services:
  apple-si-gaming-db_postgres:
    platform: linux/amd64
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/apple-si-gaming-db/data
    
  # mysql:
  #   platform: linux/amd64
  #   image: mysql:8.0.28
  #   container_name: turborepo_mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: turborepo
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #     - database:/var/lib/mysql
