# fly.toml file generated for steamed-apples-staging-remix-app on 2023-03-13T20:05:58-07:00

app = "steamed-apples-staging-remix-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "yarn run db:migrate:deploy"

# [build]
  # image = "registry.fly.io/steamed-apples-staging-remix-app@sha256:eb1ff8db59322487301229c1c09cf44c331beb402d540357f8245e6d35c0cc11"

[env]
  NODE_ENV = "production"
  REMIX_APP_PORT = "8080"
  PRIMARY_REGION = "lax"
  LOGGER_LOG_LEVEL = "debug"
  LOGGER_SERVICE_LABEL = "apps-remix-app-staging"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "10s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
