# fly.toml file generated for steamed-apples-backend-ops on 2023-02-27T18:49:53-07:00

app = "steamed-apples-backend-ops"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  # release_command = "yarn run db:migrate:deploy"

[env]
  BACKEND_OPS_BATCH_SIZE = 198
  BACKEND_OPS_DATA_DOWNLOAD_ATTEMPTED = 1
  BACKEND_OPS_INITIAL_PAGE = 0
  BACKEND_OPS_DAYS_SINCE_SYNC=5
  NODE_ENV = "production"
  LOG_LEVEL = "debug"
  LOGGER_SERVICE_LABEL = "apps-backend-ops"

[experimental]
  auto_rollback = true
