app = "apple-si-gaming-db-backend-ops"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# [build]
  # image = "registry.fly.io/apple-si-gaming-db-backend-ops:deployment-01GCZWKMXRHPRGS85WFNJETKSN"

[env]
  NODE_ENV = "production"
  ASGD_INITIAL_PAGE=0
  ASGD_BATCH_SIZE=198
  ASGD_DATA_DOWNLOAD_ATTEMPTED=0

[deploy]
  release_command = "yarn run db:migrate:deploy"

[experimental]
  allowed_public_ports = []
  auto_rollback = true