# fly.toml file generated for steamed-apples-backend-ops on 2023-02-27T18:49:53-07:00

app = "steamed-apples-backend-ops"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "yarn run db:migrate:deploy"

[env]
  ASGD_BATCH_SIZE = 198
  ASGD_DATA_DOWNLOAD_ATTEMPTED = 0
  ASGD_INITIAL_PAGE = 0
  NODE_ENV = "production"

[experimental]
  auto_rollback = true
