# fly.toml file generated for steamed-apples-postgres on 2023-03-07T08:17:46-07:00

app = "steamed-apples-postgres"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"

[env]
  PRIMARY_REGION = "lax"

[metrics]
  port = 9187
  path = "/metrics"

[mounts]
  destination = "/data"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/vm"

[[services]]
  protocol = "tcp"
  internal_port = 5432

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

[[services]]
  protocol = "tcp"
  internal_port = 5433

  [[services.ports]]
    port = 5433
    handlers = ["pg_tls"]
